server:
  port: ${PORT:5000}

spring:
  datasource:
    url: jdbc:mysql://localhost/cms?useSSL=false&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: AZs4buJS6F
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    hibernate.ddl-auto: update
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console.enabled: true
